project_id = "dtbiuqchjladvnnaymit"

[functions.deen-coach]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = false

[functions.send-push]
verify_jwt = false
